In [18]:
import numpy as np
import matplotlib.pyplot as plt
import cv2
from scipy import interpolate

# Question 1

In [19]:
def apply_mat(im, mat):
  return np.stack([np.sum(im * mat[i:i+1, :], axis=1) for i in range(3)], axis=1)

im = np.array([[0.8, 0.8, 0.8],
               [0.5, 0.5, 0.5],
               [1.0, 0.2, 0],
               [0.6, 0, 0]], np.float32)

RGB2YUV = np.array([[0.299, 0.587, 0.114],
                    [-0.14713, -0.28886, 0.436],
                    [0.615, -0.51499, -0.10001]], np.float32)
np.set_printoptions(precision=3, suppress=True)

In [20]:
#@title 1(a)
print(apply_mat(im, RGB2YUV))

[[ 0.8    0.     0.   ]
 [ 0.5    0.     0.   ]
 [ 0.416 -0.205  0.512]
 [ 0.179 -0.088  0.369]]


In [21]:
print(im.dot(RGB2YUV.T))

[[ 0.8    0.     0.   ]
 [ 0.5    0.     0.   ]
 [ 0.416 -0.205  0.512]
 [ 0.179 -0.088  0.369]]


In [22]:
#@title 1(b)
gray = np.mean(im, axis=1)
print(gray)

[0.8 0.5 0.4 0.2]


In [23]:
#@title 1(c)
gray_gained = np.clip(gray * 2, 0.0, 1.0)
print(gray_gained)

[1.  1.  0.8 0.4]


In [7]:
#@title 1(d)
gamma_gray = np.power(gray, 1/2.2)
ratio = gamma_gray / gray
print(ratio)

[1.129 1.459 1.648 2.406]


In [8]:
gamma_rgb = np.clip(im * ratio[..., np.newaxis], 0.0, 1.0)
print(gamma_rgb)

[[0.904 0.904 0.904]
 [0.73  0.73  0.73 ]
 [1.    0.33  0.   ]
 [1.    0.    0.   ]]


# Question 3

In [24]:
im = np.array([[.2, .2, .8],
               [.2, .2, .9],
               [.2, .2, .8]], np.float32)
kernel = np.array([[0.0, 0.1, 0.0],
                   [0.1, 0.6, 0.1],
                   [0.0, 0.1, 0.0]], np.float32)
np.set_printoptions(precision=3, suppress=True)

In [10]:
#@title Question 3a

print(cv2.filter2D(im, -1, kernel, borderType=cv2.BORDER_REPLICATE))

[[0.2  0.26 0.75]
 [0.2  0.27 0.81]
 [0.2  0.26 0.75]]


In [11]:
#@title Question 3b

i_kernel = np.zeros((3, 3), np.float32)
i_kernel[1, 1] = 1
sharpen_kernel = 2 * i_kernel - kernel
print(sharpen_kernel)
print(cv2.filter2D(im, -1, sharpen_kernel, borderType=cv2.BORDER_REPLICATE))

[[ 0.  -0.1  0. ]
 [-0.1  1.4 -0.1]
 [ 0.  -0.1  0. ]]
[[0.2  0.14 0.85]
 [0.2  0.13 0.99]
 [0.2  0.14 0.85]]


In [12]:
#@title Question 3c

print(cv2.medianBlur(im, 3))

[[0.2 0.2 0.8]
 [0.2 0.2 0.8]
 [0.2 0.2 0.8]]


# Question 4

In [13]:
im = np.array([[.1, .1, .0, .0,],
               [.3, .3, .2, .2,],
               [.4, .4, .5, .5,],
               [.6, .6, .7, .7,]], np.float32)

In [14]:
#@title 4(a)

print(np.rot90(im, -1))

[[0.6 0.4 0.3 0.1]
 [0.6 0.4 0.3 0.1]
 [0.7 0.5 0.2 0. ]
 [0.7 0.5 0.2 0. ]]


In [ ]:
#@title 4(b)

x = np.array(range(4))
y = np.array(range(4))
X, Y = np.meshgrid(x, y)
f = interpolate.interp2d(X, Y, im, kind='linear', )
out = np.zeros((4, 4), np.float32)
for i in range(4):
  for j in range(4):
    out[i, j] = f(x[j], np.clip(y[i] - .5, 0, 3))

print(out)

In [ ]:
#@title 4(b) -v2


In [16]:
new_im = np.zeros((5,4),np.float32)
out_img = np.zeros((4,4),np.float32)
new_im[0, :] = im[0, :]
new_im[1:5, :] = im[0:4, :]
for i in range(4):
  out_img[i,:] = (new_im[i,:]+ new_im[i+1,:]) / 2
print(out_img)

[[0.1  0.1  0.   0.  ]
 [0.2  0.2  0.1  0.1 ]
 [0.35 0.35 0.35 0.35]
 [0.5  0.5  0.6  0.6 ]]


In [17]:
#@title 4(c)
out = np.zeros((2, 2), np.float32)
h,w = im.shape
step_h = h // 2
step_w = w // 2
for i in range(2):
  for j in range(2):
    out[j][i] = np.sum(im[j*step_h:(j+1)*step_h, i*step_w:(i+1)*step_w ]) / (step_h * step_w)
print(out)

[[0.2 0.1]
 [0.5 0.6]]
